--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- ======Barak Filter====== --

--------------- HEADER SECTION ---------------
local header_record = {
  { name = "prefix", data_type = "uint16_t" },
  { name = "source_device", data_type = "uint16_t" },
  { name = "destination_device", data_type = "uint16_t" },
  { name = "message_type", data_type = "uint8_t", type_id = true },
  { name = "msg_len", data_type = "uint8_t" },
}
----------------------------------------------

--------------- MESSAGES SECTION -------------

--------------- ALLREPORT_REPLY ---------------

local AllReport_Reply = {
  name = "AllReport_Reply",
  fields = {
    { name = "flight_numer", data_type = "flight_numer_t" },
    { name = "aircraft_tail_number", data_type = "string", delimiter = "null", escape = "00", charset = "ASCII" },
    { name = "IATA_airport_code_of_nearest_airport", data_type = "string", delimiter = "null", escape = "00", charset = "ASCII" },
  }
}

----------------------------------------------

--------------- LOCATION_REPORT ---------------

local location_report = {
  name = "location_report",
  fields = {
    { name = "current_time", data_type = "uint64_t", valid_value = { min = 0, max = 9.2233720368548e+18 } },
    { name = "altitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "latitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "longitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "speed", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "bearing", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

----------------------------------------------

--------------- TARGETS_REPORT ---------------

local Targets_report = {
  name = "Targets_report",
  fields = {
    { name = "number_of_targets_array_size", data_type = "uint8_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "number_of_targets", data_type = "int40_t", valid_value = { min = 0, max = 10 }, optional = { type = optional_type.ARRAY, depend = "./number_of_targets_array_size" } },
  }
}

----------------------------------------------

--------------- ENGINES_STATUS_REPORT_ ---------------

local engines_status_report_ = {
  name = "engines_status_report_",
  fields = {
    { name = "right_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "right_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

----------------------------------------------

--------------- ALLREPORTS_REQUEST ---------------

local AllReports_Request = {
  name = "AllReports_Request",
  fields = {
    { name = "static_array", data_type = "uint0_t" },
  }
}

----------------------------------------------

--------------- STRUCTS SECTION --------------

-- FLIGHT_NUMER
local flight_numer = {
  { name = "letters", data_type = "flight_number_letters_t" },
  { name = "digits", data_type = "string", escape = "\\", charset = "ASCII" },
  { name = "null_terminator", data_type = "string", delimiter = "null", escape = "\\", charset = "ASCII" },
}
-- FLIGHT_NUMBER_LETTERS
local flight_number_letters = {
  { name = "letters", data_type = "string", escape = "\\", charset = "ASCII" },
}

-----------------------------------------------

--------------- Struct Table Definition ---------------

local structs = {
  ["flight_numer_t"] = flight_numer,
  ["flight_number_letters_t"] = flight_number_letters
}

-------------------------------------------------------

-------------- Message Table Definition ---------------

local messages = {
  [21] = AllReport_Reply,
  [10] = location_report,
  [11] = Targets_report,
  [12] = engines_status_report_,
  [20] = AllReports_Request
}

-------------------------------------------------------

generate_filter_code(header_record, messages)