--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- ======ground_control_v9 Filter====== --

--------------- HEADER SECTION ---------------
local header_record = {
  { name = "prefix", data_type = "uint16_t" },
  { name = "source_device", data_type = "uint16_t" },
  { name = "destination_device", data_type = "uint16_t" },
  { name = "message_type", data_type = "uint8_t", type_id = true },
  { name = "body_length_in_bytes", data_type = "uint16_t", valid_value = { min = 0, max = 418 } },
  { name = "sequential_number", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  { name = "checksum", data_type = "uint16_t" },
}
----------------------------------------------

--------------- MESSAGES SECTION -------------

--------------- ALLREPORT_REPLY ---------------

local AllReport_Reply = {
  name = "AllReport_Reply",
  fields = {
    { name = "flight_number", data_type = "string", delimiter = "null", escape = "00", charset = "ASCII" },
    { name = "aircraft_tail_number", data_type = "string", delimiter = "null", escape = "00", charset = "ASCII" },
    { name = "IATA_airport_code_of_nearest_airport", data_type = "string", delimiter = "null", escape = "00", charset = "ASCII" },
  }
}

----------------------------------------------

--------------- LOCATION_REPORT ---------------

local location_report = {
  name = "location_report",
  fields = {
    { name = "current_time", data_type = "uint64_t", valid_value = { min = 0, max = 9223372036854775807 } },
    { name = "altitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "latitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "longitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "speed", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "bearing", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

----------------------------------------------

--------------- TARGETS_REPORT ---------------

local Targets_report = {
  name = "Targets_report",
  fields = {
    { name = "number_of_targets_array_size", data_type = "uint8_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "number_of_targets", data_type = "int64_t", valid_value = { min = 0, max = 9223372036854775807 }, optional = { type = optional_type.ARRAY, depend = "./number_of_targets_array_size" } },
  }
}

----------------------------------------------

--------------- ENGINES_STATUS_REPORT_ ---------------

local engines_status_report_ = {
  name = "engines_status_report_",
  fields = {
    { name = "right_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "right_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

----------------------------------------------

--------------- ALLREPORTS_REQUEST ---------------

local AllReports_Request = {
  name = "AllReports_Request",
  fields = {

  }
}

----------------------------------------------

--------------- STRUCTS SECTION --------------


-----------------------------------------------

--------------- Struct Table Definition ---------------

local structs = 
}

-------------------------------------------------------

-------------- Message Table Definition ---------------

local messages = {
  [21] = AllReport_Reply,
  [10] = location_report,
  [11] = Targets_report,
  [12] = engines_status_report_,
  [20] = AllReports_Request
}

-------------------------------------------------------

generate_filter_code(header_record, messages)