--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- Header Message
local header_record = {
  { name = "version", data_type = "int8_t", valid_value = { min = 0, max = 5 } },
  { name = "msg_type", data_type = "uint8_t", valid_value = { enum = { 1, 2 } }, type_id = true },
  { name = "family", data_type = "int8_t", valid_value = { min = 0, max = 6 } },
  { name = "len", data_type = "int16_t", valid_value = { min = 0, max = 2147483647 } },
  { name = "padding", data_type = "int8_t" },

}

-- HELLO_MSG
local hello_msg = {
  name = "hello_msg",
  fields = {
    { name = "bienvenue", data_type = "int16_t", valid_value = { min = 2, max = 18047 } },
    { name = "welcome", data_type = "float32_t", valid_value = { min = 4, max = 9 } },
    { name = "padding", data_type = "int64_t" },
    { name = "ok", data_type = "int8_t", valid_value = { min = 0, max = 2147483647 } },
  
  }
}

-- BYE_MSG
local bye_msg = {
  name = "bye_msg",
  fields = {
    { name = "how_are_u", data_type = "uint8_t" },
    { name = "goodbye", data_type = "int8_t", valid_value = { min = 2, max = 3 } },
    { name = "padding", data_type = "uint64_t" },
    { name = "have_a_nice_day", data_type = "uint8_t" },
  
  }
}


ֿֿֿֿֿ-- Structs Definition Table
local structs = {
}

-- Messages Definition Table
local messages = {
  [1] = hello_msg,
  [2] = bye_msg,
}

generate_filter_code(header_record, messages, structs)