--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

--header
local header_record = {
  { name = "version", data_type = "int8_t", valid_value = { min = 0, max = 5 } },
  { name = "msg_type", data_type = "uint8_t", valid_value = { enum = { 1, 2 } }, type_id = true },
  { name = "family", data_type = "int8_t", valid_value = { min = 0, max = 6 } },
  { name = "len", data_type = "int16_t", valid_value = { min = 0, max = 2147483647 } },
  { name = "padding", data_type = "int8_t", valid_value = { exact = { 0 } } },
}

local hello_msg = {
  name = "hello_msg",
  fields = {
    { name = "bienvenue", data_type = "int16_t", valid_value = { min = 2, max = 18047 } },
    { name = "welcome", data_type = "float", valid_value = { min = 4, max = 9 } },
    { name = "constant", data_type = "uint8_t", valid_value = { exact = { 0xAA55 } } },
    { name = "gap", data_type = "uint64_t" },
    { name = "padding", data_type = "int64_t", valid_value = { exact = { 0 } } },
    { name = "ok", data_type = "int8_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

local bye_msg = {
  name = "bye_msg",
  fields = {
    { name = "how_are_u", data_type = "uint8_t" },
    { name = "goodbye", data_type = "int8_t", valid_value = { min = 2, max = 3 } },
    { name = "padding", data_type = "uint64_t" },
    { name = "have_a_nice_day", data_type = "uint8_t" },
  }
}

-- structs table
local structs = {
}

--messages table
local messages = {
  [1] = hello_msg,
  [2] = bye_msg
}

generate_filter_code(header_record, messages)