--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- ======Demo Ground Control Protocol Filter====== --

--------------- HEADER SECTION ---------------
local header_record = {
  { name = "prefix", data_type = "uint16_t" },
  { name = "source_device", data_type = "uint16_t" },
  { name = "destination_device", data_type = "uint16_t" },
  { name = "message_type", data_type = "uint8_t", type_id = true },
  { name = "body_length_in_bytes", data_type = "uint16_t" },
  { name = "sequential_number", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  { name = "checksum", data_type = "uint32_t" },
}
----------------------------------------------

--------------- MESSAGES SECTION -------------

--------------- ALLREPORT_REPLY ---------------

local AllReport_Reply = {
  name = "AllReport_Reply",
  fields = {
    { name = "flight_number", data_type = "string", delimiter = "null", charset = "ASCII" },
    { name = "aircraft_tail_number", data_type = "string", delimiter = "null", charset = "ASCII" },
    { name = "IATA_airport_code_of_nearest_airport", data_type = "string", delimiter = "null", charset = "ASCII" },
  }
}

----------------------------------------------

--------------- LOCATION_REPORT ---------------

local location_report = {
  name = "location_report",
  fields = {
    { name = "current_time", data_type = "uint64_t", valid_value = { min = 0, max = 9.2233720368548e+18 } },
    { name = "altitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "latitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "longitude", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "speed", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "bearing", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
  }
}

----------------------------------------------

--------------- TARGETS_REPORT ---------------

local Targets_report = {
  name = "Targets_report",
  fields = {
    { name = "number_of_targets_array_size", data_type = "uint8_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "number_of_targets", data_type = "int64_t", valid_value = { min = 0, max = 9.2233720368548e+18 }, optional = { type = optional_type.ARRAY, depend = "number_of_targets_array_size" } },
  }
}

----------------------------------------------

--------------- ENGINES_STATUS_REPORT_ ---------------

local engines_status_report_ = {
  name = "engines_status_report_",
  fields = {
    { name = "right_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_temperature", data_type = "int32_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "right_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "left_engine_RPM", data_type = "uint16_t", valid_value = { min = 0, max = 2147483647 } },
    { name = "engine_type", data_type = "int32_t", valid_value = { enum = { 1, 2, 3, 4 } } },
  }
}

----------------------------------------------

--------------- ALLREPORTS_REQUEST ---------------

local AllReports_Request = {
  name = "AllReports_Request",
  fields = {
    { name = "array_of_struct", data_type = "bits_struct", static_array_size = 10 },
    { name = "size_of_elements", data_type = "uint8_t", valid_value = { min = 0, max = 5555 } },
    { name = "dynamic_array", data_type = "light_bit", optional = { type = optional_type.ARRAY, depend = "size_of_elements" } },
  }
}

----------------------------------------------

--------------- BITFIELDS SECTION --------------

-- BIG_BIT_FIELD
local big_bit_field = {
  { name = "field5", bit_count = 5 },
  { name = "field4", bit_count = 4 },
  { name = "field3", bit_count = 3 },
  { name = "field4s", bit_count = 4 },
}
-- LIGHT_BIT
local light_bit = {
  { name = "first", bit_count = 2 },
  { name = "second", bit_count = 4 },
  { name = "rest", bit_count = 2 },
}

-----------------------------------------------

--------------- STRUCTS SECTION --------------

-- BITS_STRUCT
local bits_struct = {
  { name = "bit_one" },
  { name = "just_size", data_type = "uint16_t", valid_value = { min = 10, max = 15 } },
  { name = "big_bits" },
}
-- LIGHT_BIT
local light_bit = {
  { name = "first", bit_count = 2 },
  { name = "second", bit_count = 4 },
  { name = "rest", bit_count = 2 },
}

-----------------------------------------------

--------------- Struct Table Definition ---------------

local structs = {
  ["bits_struct_t"] = bits_struct,
  ["light_bit_t"] = light_bit
}

-------------------------------------------------------

-------------- Message Table Definition ---------------

local messages = {
  [21] = AllReport_Reply,
  [10] = location_report,
  [11] = Targets_report,
  [12] = engines_status_report_,
  [20] = AllReports_Request
}

-------------------------------------------------------

--------------- Bit Field Table Definition ---------------

local bit_fields = {
  ["light_bit_bit_array"] = light_bit,
  ["big_bit_field_bit_array"] = big_bit_field
}

-------------------------------------------------------

generate_filter_code(header_record, messages)