--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- ======Simplest Filter====== --

--------------- HEADER SECTION ---------------
local header_record = {
  { name = "version", data_type = "int8_t", valid_value = { min = 0, max = 5 } },
  { name = "msg_type", data_type = "uint8_t", valid_value = { enum = { 1, 21 } }, type_id = true },
  { name = "family", data_type = "int8_t", valid_value = { min = 0, max = 6 } },
  { name = "len", data_type = "int16_t", valid_value = { min = 0, max = 2147483647 } },
  { name = "padding", data_type = "int8_t", valid_value = { exact = { 0 } } }
}
----------------------------------------------

--------------- MESSAGES SECTION -------------

--------------- HELLO_MSG ---------------

local hello_msg = {
  name = "hello_msg",
  fields = {
    { name = "bienvenue", data_type = "int16_t", valid_value = { min = 2, max = 18047 } },
    { name = "welcome", data_type = "float", valid_value = { min = 4, max = 9 } },
    { name = "padding", data_type = "int64_t", valid_value = { exact = { 0 } } },
    { name = "ok", data_type = "int8_t", valid_value = { min = 0, max = 2147483647 } }
  }
}

----------------------------------------------

--------------- STRUCTS_EXMAPLE_MSG ---------------

local structs_exmaple_msg = {
  name = "structs_exmaple_msg",
  fields = {
    { name = "flight_number", data_type = "flight_number_t" }
  }
}

----------------------------------------------

--------------- STRUCTS SECTION --------------

-- FLIGHT_NUMBER_LETTERS
local flight_number_letters = {
  { name = "version-letters", data_type = "int8_t", valid_value = { min = 0, max = 5 } }
}
-- FLIGHT_NUMBER_DIGITS
local flight_number_digits = {
  { name = "version-digits", data_type = "int8_t", valid_value = { min = 0, max = 5 } }
}
-- FLIGHT_NUMBER
local flight_number = {
  { name = "letters", data_type = "flight_number_letters_t" },
  { name = "digits", data_type = "flight_number_digits_t" }
}

-----------------------------------------------

--------------- Struct Table Definition ---------------

local structs = {
  ["flight_number_t"] = flight_number,
  ["flight_number_letters_t"] = flight_number_letters,
  ["flight_number_digits_t"] = flight_number_digits
}

-------------------------------------------------------

-------------- Message Table Definition ---------------

local messages = {
  [1] = hello_msg,
  [21] = structs_exmaple_msg
}

-------------------------------------------------------

generate_filter_code(header_record, messages)