--[[
	This Lua Code is generated by the Filter-Garden Project "Azikon"
]]

-- ======DIS Filter====== --

--------------- HEADER SECTION ---------------
local header_record = {
  { name = "Protocol_version", data_type = "int8_t", valid_value = { min = 0, max = 10 } },
  { name = "Exercise_id", data_type = "uint8_t", valid_value = { min = 0, max = 255 } },
  { name = "Pdu Type", data_type = "uint8_t", type_id = true },
  { name = "Protocol Family", data_type = "uint8_t", valid_value = { min = 0, max = 6 } },
  { name = "timestamp", data_type = "int32_t", valid_value = { min = 0, max = 42000000 } },
  { name = "Length", data_type = "uint16_t", valid_value = { min = 0, max = 2000 } },
}
----------------------------------------------

--------------- MESSAGES SECTION -------------

--------------- OTHER ---------------

local Other = {
  name = "Other",
  fields = {

  }
}

----------------------------------------------

--------------- ENTITY_STATE ---------------

local Entity_State = {
  name = "Entity_State",
  fields = {
    { name = "Entity_id", data_type = "Entity_id_t" },
    { name = "Force Id", data_type = "uint8_t", valid_value = { min = 0, max = 3 } },
    { name = "Entity_type", data_type = "Entity_type_t" },
    { name = "Linear Velocity", data_type = "Linear Velocity_t" },
  }
}

----------------------------------------------

--------------- FIRE ---------------

local Fire = {
  name = "Fire",
  fields = {

  }
}

----------------------------------------------

--------------- DETONATION ---------------

local Detonation = {
  name = "Detonation",
  fields = {

  }
}

----------------------------------------------

--------------- DATA ---------------

local Data = {
  name = "Data",
  fields = {

  }
}

----------------------------------------------

--------------- ELECTROMAGNETIC_EMISSION ---------------

local Electromagnetic_emission = {
  name = "Electromagnetic_emission",
  fields = {

  }
}

----------------------------------------------

--------------- ACKNOWLEDGE ---------------

local Acknowledge = {
  name = "Acknowledge",
  fields = {

  }
}

----------------------------------------------

--------------- REMOVE_ENTITY ---------------

local Remove_Entity = {
  name = "Remove_Entity",
  fields = {

  }
}

----------------------------------------------

--------------- START ---------------

local Start = {
  name = "Start",
  fields = {

  }
}

----------------------------------------------

--------------- STOP ---------------

local Stop = {
  name = "Stop",
  fields = {

  }
}

----------------------------------------------

--------------- DATA_QUERY ---------------

local Data_Query = {
  name = "Data_Query",
  fields = {
    { name = "prim1", data_type = "double", valid_value = { min = 3.14, max = 7.22 } },
    { name = "prim2", data_type = "int16_t", valid_value = { min = 0, max = 5 } },
    { name = "marking", data_type = "marking_t" },
  }
}

----------------------------------------------

--------------- STRUCTS SECTION --------------

-- SUB_B
local sub_b = {
  { name = "ofhex", data_type = "uint0_t" },
}
-- ENTITY_ID
local Entity_id = {
  { name = "Site", data_type = "uint16_t", valid_value = { min = 0, max = 65536 } },
  { name = "application", data_type = "uint16_t", valid_value = { min = 0, max = 65536 } },
  { name = "Entity Identifier", data_type = "uint16_t", valid_value = { min = 0, max = 65536 } },
}
-- ENTITY_TYPE
local Entity_type = {
  { name = "Kind Field", data_type = "int8_t", valid_value = { min = 0, max = 255 } },
  { name = "Domain Field", data_type = "int8_t", valid_value = { min = 0, max = 255 } },
  { name = "Country field", data_type = "uint16_t", valid_value = { min = 0, max = 65535 } },
  { name = "Catagory Field", data_type = "uint8_t", valid_value = { min = 0, max = 255 } },
  { name = "Subcategory Field", data_type = "uint8_t", valid_value = { min = 0, max = 255 } },
  { name = "Specific Field", data_type = "uint8_t", valid_value = { min = 0, max = 255 } },
  { name = "Extra Field", data_type = "uint8_t", valid_value = { min = 0, max = 255 } },
}
-- LINEAR_VELOCITY
local Linear_Velocity = {
  { name = "First Vector Component", data_type = "float", valid_value = { min = -5000, max = 5000 } },
  { name = "Second Vector Component", data_type = "float", valid_value = { min = -5000, max = 5000 } },
  { name = "Third Vector Component", data_type = "float", valid_value = { min = -5000, max = 5000 } },
}
-- MARKING
local marking = {
  { name = "application ", data_type = "Entity_id_t" },
  { name = "site", data_type = "Entity_id_t" },
  { name = "marking_type", data_type = "Entity_type_t" },
  { name = "timestamp", data_type = "uint32_t", valid_value = { min = 0, max = 10000000 } },
  { name = "marking_velocity", data_type = "Linear Velocity_t" },
  { name = "SuperSub", data_type = "sub_a_t" },
}
-- SUB_A
local sub_a = {
  { name = "first sub", data_type = "sub_b_t" },
  { name = "second sub", data_type = "sub_b_t" },
}

-----------------------------------------------

--------------- Struct Table Definition ---------------

local structs = {
  ["marking_t"] = marking,
  ["Entity_id_t"] = Entity_id,
  ["Entity_type_t"] = Entity_type,
  ["Linear_Velocity_t"] = Linear_Velocity,
  ["sub_a_t"] = sub_a,
  ["sub_b_t"] = sub_b
}

-------------------------------------------------------

-------------- Message Table Definition ---------------

local messages = {
  [0] = Other,
  [1] = Entity_State,
  [2] = Fire,
  [3] = Detonation,
  [20] = Data,
  [23] = Electromagnetic_emission,
  [15] = Acknowledge,
  [12] = Remove_Entity,
  [13] = Start,
  [14] = Stop,
  [18] = Data_Query
}

-------------------------------------------------------

generate_filter_code(header_record, messages)