-- File: src/modules/Constants.lua

local Constants = {}

Constants.HEADER_SECTION_START = "--------------- HEADER SECTION ---------------\n"
Constants.HEADER_SECTION_END = "----------------------------------------------\n"

Constants.MESSAGES_SECTION_START = "\n--------------- MESSAGES SECTION -------------"
Constants.MESSAGES_SECTION_END = "\n----------------------------------------------"

Constants.STRUCTS_SECTION_START = "\n--------------- STRUCTS SECTION --------------\n\n"
Constants.STRUCTS_SECTION_END = "\n-----------------------------------------------\n"

Constants.BITFIELDS_SECTION_START = "\n--------------- BITFIELDS SECTION --------------\n\n"
Constants.BITFIELDS_SECTION_END = "\n-----------------------------------------------\n"

Constants.STRUCT_TABLE_SECTION_START = "\n--------------- Struct Table Definition ---------------\n\n"
Constants.STRUCT_TABLE_SECTION_END = "\n-------------------------------------------------------\n"

Constants.BITFIELD_TABLE_SECTION_START = "\n--------------- Bit Field Table Definition ---------------\n\n"
Constants.BITFIELD_TABLE_SECTION_END = "\n-------------------------------------------------------\n"

Constants.MESSAGE_TABLE_SECTION_START = "\n-------------- Message Table Definition ---------------\n\n"
Constants.MESSAGE_TABLE_SECTION_END = "\n-------------------------------------------------------\n"

Constants.GENERATED_STARTER_COMMENT = '--[[\n\tThis Lua Code is generated by the Filter-Garden Project "Azikon"\n]]\n\n'

return Constants